### ISSUE TITLE
MBean Server tab cannot be opened if there is an Agent Plugin tab open, and vice versa.

### ISSUE THREAD

**Issue by jessyec-s** [rh-jmc-team/jmc-agent-plugin#18]

**Comment by tabjy** [comment]
@jessyec-s, can you confirm this issue is still exists at this time? I can't seem to reproduce anymore.

**Comment by jessyec-s** [comment]
@tabjy yes I think the most recent commit fixed this issue :)

**Comment by tabjy** [comment]
Perfect. I'm closing this issue. Feel free to reopen it should it ever reappears.
