### ISSUE TITLE
Transformations defined in agent arguments not applied when loading dyanmically

### ISSUE THREAD

**Issue by tabjy** [rh-jmc-team/jmc-agent-plugin#4]
This issue was discovered in the review process of pr #3. When loading dynamically, the agent doesn't necessarily perform the transformation defined in the XML probes supplied as a path argument.

When the agent initializes, it creates a class file transformer. The transformer then waits for classes with pending transformations to be loaded, or to be explicitly submitted transformer with `instrumentation.retransformClasses(Class[])`.

Without the agent itself explicitly calling `instrumentation.retransformClasses(Class[])` on classes with pending transformation, such transformations will never apply.

This is an upstream issue. Corresponding tickets should be opened to JMC project once confirmed.

A current workaround would be something like:

1. When attaching the agent dynamically, specify a path to an XML config with no event defined.
2. Connect to the target JVM via JMX and execute `defineEventProbes` operation with actual event definitions
3. The JMX controller will update the registry and explicitly calls `instrumentation.retransformClasses(Class[])`

**Comment by jessyec-s** [comment]
I have opened the issue [JMC-6712](https://bugs.openjdk.java.net/browse/JMC-6712) to address this.
