### ISSUE TITLE
Display global options in Overview page

### ISSUE THREAD

**Issue by tabjy** [rh-jmc-team/jmc-agent-plugin#41]
Since "Live Config" page no longer displays global options (those in `<config>` tag), these options should be displayed somewhere else (`Overview Page`) looks good to me.

_Originally posted by @tabjy in https://github.com/rh-jmc-team/jmc-agent-plugin/pull/39#issuecomment-639094223_

**Comment by tabjy** [comment]
Once [JMC-6875](https://github.com/openjdk/jmc/pull/99) is merged, there will be possibilities to get global options, plus the number of events that's currently live.

**Comment by Josh-Matsuoka** [comment]
Resolved with https://github.com/rh-jmc-team/jmc-agent-plugin/pull/78
