### ISSUE TITLE
Change name of "Finish" button in Start Agent Wizard to "Start"

### ISSUE THREAD

**Issue by jessyec-s** [rh-jmc-team/jmc-agent-plugin#43]
Button might be more clear if the name was "Start" or "load" instead of finish

**Comment by tabjy** [comment]
Not sure if this is possible. The creation and logic on the "finish" button are handled by some JFace class.

**Comment by Josh-Matsuoka** [comment]
Fixed with https://github.com/rh-jmc-team/jmc-agent-plugin/pull/80
