### ISSUE TITLE
<returnvalue> should have an optionally configurable <name> property

### ISSUE THREAD

**Issue by tabjy** [rh-jmc-team/jmc-agent-plugin#61]
A second look at the agent implementation: yes, I agree with you. The `name` property should be configurable.

While the schema definition file doesn't allow a `<name>` property and will throw an error upon validation, it's a bug not catch during the [reviewing process](https://github.com/openjdk/jmc/pull/66) of [JMC-6725](https://bugs.openjdk.java.net/browse/JMC-6725).

There should be an upstream issue created to address this problem. We can just leave this at it is for now, until it gets resolved upstream.

_Originally posted by @tabjy in https://github.com/rh-jmc-team/jmc-agent-plugin/pull/59/review_comment/create_

**Comment by jessyec-s** [comment]
I have created the upstream issue [JMC-6864](https://bugs.openjdk.java.net/browse/JMC-6864)

**Comment by tabjy** [comment]
With [JMC-6864](https://bugs.openjdk.java.net/browse/JMC-6864) merged in. We should update the `jfrprobes_schema.xsd` resource in the repository.

**Comment by jessyec-s** [comment]
The upstream issue has been fixed [here](https://github.com/openjdk/jmc/pull/94)
