### ISSUE TITLE
Remove the presets tab

### ISSUE THREAD

**Issue by jessyec-s** [rh-jmc-team/jmc-agent-plugin#64]
After #62 is merged, the presets tab can be removed as the editing functionality will have been replaced by the preset manager and added wizards.

**Comment by tabjy** [comment]
Yes the editing functionality is replaced, but the applying functionality is not...?

**Comment by Josh-Matsuoka** [comment]
The presets tab was removed with https://github.com/rh-jmc-team/jmc-agent-plugin/pull/78
